/* ===== doommake-TWEAK-MAKE-TARGETS-FINAL =================================== */
/* ========================================================================== */
/* === START OF TWEAK ======================================================= */
/* ========================================================================== */
/****************************************************************************
 * TARGET: complete
 ****************************************************************************
 * Runs release, editorrelease, texturesrelease, playpal, and deco - all in
 * one pass. No distribution zip.
 * doommake complete
 ****************************************************************************/
check entry complete(args) {
    doInit();
    doAll();
    doRelease();

    doEditorRelease();

    doConvertPalettes();
    doConvertColormaps();
    doConvertFlats();
    doConvertPatches();
    doConvertTextures();
    doTexturesRelease();

    doPalette();

    doPatch(false);
    doDehWad();
}

/****************************************************************************
 * TARGET: final
 ****************************************************************************
 * Same as `complete`, but also produces the distribution zip.
 * doommake final
 ****************************************************************************/
check entry final(args) {
    doInit();
    doAll();
    doRelease();

    doEditorRelease();

    doConvertPalettes();
    doConvertColormaps();
    doConvertFlats();
    doConvertPatches();
    doConvertTextures();
    doTexturesRelease();

    doPalette();

    doPatch(false);
    doDehWad();

    doDist();
}

/* === END OF TWEAK ========================================================= */
/* ========================================================================== */
