// -- doommake-TWEAK-makeTarget
/* ========================================================================== */
/* === MODIFIED STOCK TARGETS =============================================== */
/* ========================================================================== */
/* The stock `make` and `release` targets, deleted from their original       */
/* position and re-added here so they can call the tweak functions above.    */
/* ========================================================================== */
/****************************************************************************
 * TARGET: make
 ****************************************************************************
 * Default make target.
 * [MODIFIED] Full build + release WAD, dehacked & palette WADs, no dist zip.
 * doommake
 ****************************************************************************/
check entry make(args) {
	doInit();
	doAll();
	doRelease();
	doDehWad();
	doPalette();
}
