// -- doommake-TWEAK-releaseTarget
/****************************************************************************
 * TARGET: release
 ****************************************************************************
 * [MODIFIED] Full build + release, dehacked & palette WADs, dist zip.
 * doommake release
 ****************************************************************************/
check entry release(args) {
	doInit();
	doAll();
	doRelease();
	doDehWad();
	doPalette();
	doDist();
}

/* === END OF TWEAK ========================================================= */
/* ========================================================================== */
